package vista;

import controlador.Registro;
import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import modelo.*;

public class InfoPostulante extends javax.swing.JFrame {

    /**
     * Creates new form InfoPostulante
     * @param p
     */
    public InfoPostulante(Postulante p) {
        this.initComponents();
        
        // Completación de los campos de acuerdo a las secciones de la vista
        // Datos de la ficha de postulación
        this.LblNroFolioValor.setText(String.valueOf(p.getFicha().getNroFolio()));
        this.LblFecPosValor.setText(p.getFicha().getFechaPostulacion().toString());
        this.LblReceptorValor.setText(p.getFicha().getReceptor().getNombres() + " " + p.getFicha().getReceptor().getApPaterno() + " " + p.getFicha().getReceptor().getApMaterno());
        if (p.getFoto() != null) {
            try {
                ImageIcon img = new ImageIcon(ImageIO.read(new ByteArrayInputStream(p.getFoto())));
                Icon foto = new ImageIcon(img.getImage().getScaledInstance(this.FotoPos.getWidth(), this.FotoPos.getHeight(), Image.SCALE_DEFAULT));
                this.FotoPos.setIcon(foto);
            } catch (IOException e) {
                System.out.println(e.getMessage());
                this.FotoPos.setText("SIN FOTO");
            }
        } else {
            this.FotoPos.setText("SIN FOTO");
        }
        
        // Datos Personales del Postulante
        this.TxtRunPos.setText(p.getRun() + "-" + p.getDV());
        this.TxtNomPos.setText(p.getNombres() + " " + p.getApPaterno() + " " + p.getApPaterno());
        this.TxtFecNac.setText(p.getFecNac().toString());
        this.TxtNacion.setText(p.getNacionalidad());
        this.TxtECivil.setText(p.getECivil());
        this.TxtCargas.setText(String.valueOf(p.getNCargas()));
        if (p.getIndOrg().equals("NO")) {
            this.TxtIndOrg.setText("NO");
        } else {
            this.TxtIndOrg.setText("SI");
        }
        this.TxtCarrera.setText(p.getTitulo());
        
        // Datos del Cónyuge
        if (p.getConyuge() != null) {
            this.TxtRunCon.setText(p.getConyuge().getRun() + "-" + p.getConyuge().getDV());
            this.TxtNomCon.setText(p.getConyuge().getNombres() + " " + p.getConyuge().getApPaterno() + " " + p.getConyuge().getApMaterno());
        }
        
        // Domicilio del Postulante
        this.TxtCalle.setText(p.getDireccion().substring(0, p.getDireccion().indexOf('#') - 1));
        this.TxtNumCalle.setText(p.getDireccion().substring(p.getDireccion().indexOf('#') + 1));
        this.TxtBlock.setText((p.getDepto() != null) ? p.getDepto().substring(p.getDepto().indexOf('-')) : "");
        this.TxtDepto.setText((p.getDepto() != null) ? p.getDepto().substring(0, p.getDepto().indexOf('-')) : "");
        this.TxtManzana.setText((p.getManzana() != null) ? p.getManzana() : "");
        this.TxtSitio.setText((p.getSitio() != null) ? p.getSitio() : "");
        this.TxtRegionPos.setText(p.getRegion());
        this.TxtComunaPos.setText(p.getComuna());
        
        // Contacto del Postulante
        this.TxtFonoTrab.setText(String.valueOf(p.getFonoTrab()));
        this.TxtFonoDom.setText(String.valueOf(p.getFonoDom()));
        this.TxtFonoMovil.setText(String.valueOf(p.getFonoMovil()));
        this.TxtCodPostal.setText(String.valueOf(p.getCodPostal()));
        this.TxtEmail.setText(p.getEmail());
        
        // Datos del Subsidio al que postuló
        this.TxtTituloSub.setText(p.getFicha().getTituloSubsidio());
        this.TxtRegionSub.setText(p.getFicha().getViviendaElegida().getRegion());
        this.TxtComunaSub.setText(p.getFicha().getViviendaElegida().getComuna());
        this.TxtTipoVivienda.setText(p.getFicha().getViviendaElegida().getTipo());
        this.TxtValorProp.setText(String.valueOf(p.getFicha().getViviendaElegida().getValor()));
        this.TxtMontoAhorrado.setText(String.valueOf(p.getMontoAhorrad()));
        this.TxtPtjMin.setText(String.valueOf(Registro.obtPromPtj()));
        this.TxtPtjObt.setText(String.valueOf(p.getPtjObtenido()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTituloVentana = new javax.swing.JLabel();
        LblNroFolio = new javax.swing.JLabel();
        LblNroFolioValor = new javax.swing.JLabel();
        LblFecPos = new javax.swing.JLabel();
        LblFecPosValor = new javax.swing.JLabel();
        LblReceptor = new javax.swing.JLabel();
        LblReceptorValor = new javax.swing.JLabel();
        FotoPos = new javax.swing.JLabel();
        PanDatosPersonales = new javax.swing.JPanel();
        LblRunPos = new javax.swing.JLabel();
        LblFecNac = new javax.swing.JLabel();
        LblCargas = new javax.swing.JLabel();
        LblNomPos = new javax.swing.JLabel();
        LblNacion = new javax.swing.JLabel();
        LblIndOrg = new javax.swing.JLabel();
        LblECivil = new javax.swing.JLabel();
        LblCarrera = new javax.swing.JLabel();
        TxtRunPos = new javax.swing.JTextField();
        TxtFecNac = new javax.swing.JTextField();
        TxtCargas = new javax.swing.JTextField();
        TxtNomPos = new javax.swing.JTextField();
        TxtNacion = new javax.swing.JTextField();
        TxtIndOrg = new javax.swing.JTextField();
        TxtECivil = new javax.swing.JTextField();
        TxtCarrera = new javax.swing.JTextField();
        PanDatosConyuge = new javax.swing.JPanel();
        LblRunCon = new javax.swing.JLabel();
        LblNomCon = new javax.swing.JLabel();
        TxtRunCon = new javax.swing.JTextField();
        TxtNomCon = new javax.swing.JTextField();
        PanDomicilio = new javax.swing.JPanel();
        LblCalle = new javax.swing.JLabel();
        LblBlock = new javax.swing.JLabel();
        LblRegionPos = new javax.swing.JLabel();
        LblNumCalle = new javax.swing.JLabel();
        LblDepto = new javax.swing.JLabel();
        LblComunaPos = new javax.swing.JLabel();
        LblManzana = new javax.swing.JLabel();
        LblSitio = new javax.swing.JLabel();
        TxtCalle = new javax.swing.JTextField();
        TxtBlock = new javax.swing.JTextField();
        TxtRegionPos = new javax.swing.JTextField();
        TxtDepto = new javax.swing.JTextField();
        TxtManzana = new javax.swing.JTextField();
        TxtNumCalle = new javax.swing.JTextField();
        TxtSitio = new javax.swing.JTextField();
        TxtComunaPos = new javax.swing.JTextField();
        PanContacto = new javax.swing.JPanel();
        LblFonoTrab = new javax.swing.JLabel();
        LblCodPostal = new javax.swing.JLabel();
        LblFonoDom = new javax.swing.JLabel();
        LblFonoMovil = new javax.swing.JLabel();
        LblEmail = new javax.swing.JLabel();
        TxtFonoTrab = new javax.swing.JTextField();
        TxtFonoDom = new javax.swing.JTextField();
        TxtFonoMovil = new javax.swing.JTextField();
        TxtCodPostal = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        PanDatosSubsidio = new javax.swing.JPanel();
        LblTituloSub = new javax.swing.JLabel();
        LblTipoVivienda = new javax.swing.JLabel();
        LblPtjMin = new javax.swing.JLabel();
        LblRegionSub = new javax.swing.JLabel();
        LblValorProp = new javax.swing.JLabel();
        LblPtjObt = new javax.swing.JLabel();
        LblComunaSub = new javax.swing.JLabel();
        LblMontoAhorrado = new javax.swing.JLabel();
        TxtTituloSub = new javax.swing.JTextField();
        TxtTipoVivienda = new javax.swing.JTextField();
        TxtPtjMin = new javax.swing.JTextField();
        TxtRegionSub = new javax.swing.JTextField();
        TxtComunaSub = new javax.swing.JTextField();
        TxtValorProp = new javax.swing.JTextField();
        TxtMontoAhorrado = new javax.swing.JTextField();
        TxtPtjObt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Información del postulante");
        setName("InfoPostulante"); // NOI18N
        setResizable(false);

        LblTituloVentana.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblTituloVentana.setText("<html><p align=\"center\">INFORMACIÓN DEL POSTULANTE AL<br />SISTEMA INTEGRADO DE SUBSIDIO HABITACIONAL</p></html>");

        LblNroFolio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblNroFolio.setText("FOLIO NRO:");

        LblNroFolioValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblNroFolioValor.setText("<123456789>");

        LblFecPos.setText("Fecha postulación:");

        LblFecPosValor.setText("00/00/0000");

        LblReceptor.setText("Receptor de la postulación:");

        LblReceptorValor.setText("<Nombres ApellidoPat ApellidoMat>");

        PanDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales del Postulante"));

        LblRunPos.setText("Cédula de Identidad Nº:");

        LblFecNac.setText("Fecha nacimiento:");

        LblCargas.setText("Total cargas familiares:");

        LblNomPos.setText("Nombre completo:");

        LblNacion.setText("Nacionalidad:");

        LblIndOrg.setText("Pueblo Indígena u Originario:");

        LblECivil.setText("Estado civil:");

        LblCarrera.setText("Título:");

        javax.swing.GroupLayout PanDatosPersonalesLayout = new javax.swing.GroupLayout(PanDatosPersonales);
        PanDatosPersonales.setLayout(PanDatosPersonalesLayout);
        PanDatosPersonalesLayout.setHorizontalGroup(
            PanDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblRunPos)
                    .addComponent(LblFecNac)
                    .addComponent(LblCargas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(PanDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtFecNac, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(TxtRunPos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblNacion)
                            .addComponent(LblNomPos)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(TxtCargas, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblIndOrg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(TxtNacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblECivil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtECivil))
                    .addComponent(TxtNomPos)
                    .addGroup(PanDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(TxtIndOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblCarrera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtCarrera)))
                .addContainerGap())
        );
        PanDatosPersonalesLayout.setVerticalGroup(
            PanDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblRunPos)
                    .addComponent(LblNomPos)
                    .addComponent(TxtRunPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNomPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblFecNac)
                    .addComponent(LblNacion)
                    .addComponent(LblECivil)
                    .addComponent(TxtFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtECivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCargas)
                    .addComponent(LblIndOrg)
                    .addComponent(LblCarrera)
                    .addComponent(TxtCargas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtIndOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        LblRunPos.getAccessibleContext().setAccessibleDescription("");

        PanDatosConyuge.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Cónyuge"));

        LblRunCon.setText("Cédula de Identidad Nº cónyuge:");

        LblNomCon.setText("Nombre completo cónyuge:");

        javax.swing.GroupLayout PanDatosConyugeLayout = new javax.swing.GroupLayout(PanDatosConyuge);
        PanDatosConyuge.setLayout(PanDatosConyugeLayout);
        PanDatosConyugeLayout.setHorizontalGroup(
            PanDatosConyugeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanDatosConyugeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblRunCon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtRunCon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblNomCon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtNomCon)
                .addContainerGap())
        );
        PanDatosConyugeLayout.setVerticalGroup(
            PanDatosConyugeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanDatosConyugeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanDatosConyugeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblRunCon)
                    .addComponent(LblNomCon)
                    .addComponent(TxtRunCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNomCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanDomicilio.setBorder(javax.swing.BorderFactory.createTitledBorder("Domicilio del Postulante"));

        LblCalle.setText("Calle:");

        LblBlock.setText("Block:");

        LblRegionPos.setText("Región:");

        LblNumCalle.setText("Número:");

        LblDepto.setText("Departamento:");

        LblComunaPos.setText("Comuna:");

        LblManzana.setText("Manzana:");

        LblSitio.setText("Sitio:");

        javax.swing.GroupLayout PanDomicilioLayout = new javax.swing.GroupLayout(PanDomicilio);
        PanDomicilio.setLayout(PanDomicilioLayout);
        PanDomicilioLayout.setHorizontalGroup(
            PanDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanDomicilioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanDomicilioLayout.createSequentialGroup()
                        .addGroup(PanDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblBlock)
                            .addComponent(LblCalle))
                        .addGap(19, 19, 19)
                        .addGroup(PanDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanDomicilioLayout.createSequentialGroup()
                                .addComponent(TxtBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LblDepto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LblManzana)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtManzana, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TxtCalle)))
                    .addGroup(PanDomicilioLayout.createSequentialGroup()
                        .addComponent(LblRegionPos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtRegionPos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblComunaPos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtComunaPos)
                    .addGroup(PanDomicilioLayout.createSequentialGroup()
                        .addComponent(LblSitio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtSitio))
                    .addGroup(PanDomicilioLayout.createSequentialGroup()
                        .addComponent(LblNumCalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtNumCalle)))
                .addContainerGap())
        );
        PanDomicilioLayout.setVerticalGroup(
            PanDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanDomicilioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCalle)
                    .addComponent(LblNumCalle)
                    .addComponent(TxtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNumCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblBlock)
                    .addComponent(LblDepto)
                    .addComponent(LblManzana)
                    .addComponent(LblSitio)
                    .addComponent(TxtBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtManzana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSitio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblRegionPos)
                    .addComponent(LblComunaPos)
                    .addComponent(TxtRegionPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtComunaPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanContacto.setBorder(javax.swing.BorderFactory.createTitledBorder("Contacto del Postulante"));

        LblFonoTrab.setText("Teléfono trabajo:");

        LblCodPostal.setText("Código postal:");

        LblFonoDom.setText("Teléfono domicilio:");

        LblFonoMovil.setText("Teléfono móvil:");

        LblEmail.setText("E-mail:");

        javax.swing.GroupLayout PanContactoLayout = new javax.swing.GroupLayout(PanContacto);
        PanContacto.setLayout(PanContactoLayout);
        PanContactoLayout.setHorizontalGroup(
            PanContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblFonoTrab)
                    .addComponent(LblCodPostal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtCodPostal)
                    .addComponent(TxtFonoTrab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanContactoLayout.createSequentialGroup()
                        .addComponent(LblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanContactoLayout.createSequentialGroup()
                        .addComponent(LblFonoDom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtFonoDom, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblFonoMovil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtFonoMovil)))
                .addContainerGap())
        );
        PanContactoLayout.setVerticalGroup(
            PanContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblFonoTrab)
                    .addComponent(LblFonoDom)
                    .addComponent(LblFonoMovil)
                    .addComponent(TxtFonoTrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFonoDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFonoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCodPostal)
                    .addComponent(LblEmail)
                    .addComponent(TxtCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanDatosSubsidio.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Subsidio al que postuló"));

        LblTituloSub.setText("Título al cual postula:");

        LblTipoVivienda.setText("Tipo de vivienda:");

        LblPtjMin.setText("Puntaje Mínimo para obtener subsidio:");

        LblRegionSub.setText("Región:");

        LblValorProp.setText("Valor de la propiedad:");

        LblPtjObt.setText("Puntaje obtenido:");

        LblComunaSub.setText("Comuna:");

        LblMontoAhorrado.setText("Monto Ahorrado:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("(corresponde al puntaje promedio obtenido entre todos los postulantes)");

        javax.swing.GroupLayout PanDatosSubsidioLayout = new javax.swing.GroupLayout(PanDatosSubsidio);
        PanDatosSubsidio.setLayout(PanDatosSubsidioLayout);
        PanDatosSubsidioLayout.setHorizontalGroup(
            PanDatosSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanDatosSubsidioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanDatosSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanDatosSubsidioLayout.createSequentialGroup()
                        .addGroup(PanDatosSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTituloSub)
                            .addComponent(LblTipoVivienda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanDatosSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtTituloSub)
                            .addComponent(TxtTipoVivienda, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanDatosSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanDatosSubsidioLayout.createSequentialGroup()
                                .addComponent(LblRegionSub)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtRegionSub, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanDatosSubsidioLayout.createSequentialGroup()
                                .addComponent(LblValorProp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtValorProp)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanDatosSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanDatosSubsidioLayout.createSequentialGroup()
                                .addComponent(LblMontoAhorrado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtMontoAhorrado))
                            .addGroup(PanDatosSubsidioLayout.createSequentialGroup()
                                .addComponent(LblComunaSub)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtComunaSub))))
                    .addGroup(PanDatosSubsidioLayout.createSequentialGroup()
                        .addGroup(PanDatosSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanDatosSubsidioLayout.createSequentialGroup()
                                .addComponent(LblPtjMin)
                                .addGap(150, 150, 150))
                            .addGroup(PanDatosSubsidioLayout.createSequentialGroup()
                                .addGroup(PanDatosSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(PanDatosSubsidioLayout.createSequentialGroup()
                                        .addGap(193, 193, 193)
                                        .addComponent(TxtPtjMin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(LblPtjObt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtPtjObt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)))
                .addContainerGap())
        );
        PanDatosSubsidioLayout.setVerticalGroup(
            PanDatosSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanDatosSubsidioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanDatosSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTituloSub)
                    .addComponent(LblRegionSub)
                    .addComponent(LblComunaSub)
                    .addComponent(TxtTituloSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtRegionSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtComunaSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanDatosSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTipoVivienda)
                    .addComponent(LblValorProp)
                    .addComponent(LblMontoAhorrado)
                    .addComponent(TxtTipoVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtValorProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtMontoAhorrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanDatosSubsidioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPtjMin)
                    .addComponent(TxtPtjMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPtjObt)
                    .addComponent(TxtPtjObt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FotoPos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblFecPos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LblFecPosValor)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(LblNroFolio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LblNroFolioValor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(LblReceptor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LblReceptorValor))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(LblTituloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanDatosPersonales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanDatosConyuge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanDatosSubsidio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(BtnVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblTituloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblNroFolio)
                            .addComponent(LblNroFolioValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblFecPos)
                            .addComponent(LblFecPosValor)
                            .addComponent(LblReceptor)
                            .addComponent(LblReceptorValor)))
                    .addComponent(FotoPos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanDatosConyuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanDatosSubsidio, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel FotoPos;
    private javax.swing.JLabel LblBlock;
    private javax.swing.JLabel LblCalle;
    private javax.swing.JLabel LblCargas;
    private javax.swing.JLabel LblCarrera;
    private javax.swing.JLabel LblCodPostal;
    private javax.swing.JLabel LblComunaPos;
    private javax.swing.JLabel LblComunaSub;
    private javax.swing.JLabel LblDepto;
    private javax.swing.JLabel LblECivil;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblFecNac;
    private javax.swing.JLabel LblFecPos;
    private javax.swing.JLabel LblFecPosValor;
    private javax.swing.JLabel LblFonoDom;
    private javax.swing.JLabel LblFonoMovil;
    private javax.swing.JLabel LblFonoTrab;
    private javax.swing.JLabel LblIndOrg;
    private javax.swing.JLabel LblManzana;
    private javax.swing.JLabel LblMontoAhorrado;
    private javax.swing.JLabel LblNacion;
    private javax.swing.JLabel LblNomCon;
    private javax.swing.JLabel LblNomPos;
    private javax.swing.JLabel LblNroFolio;
    private javax.swing.JLabel LblNroFolioValor;
    private javax.swing.JLabel LblNumCalle;
    private javax.swing.JLabel LblPtjMin;
    private javax.swing.JLabel LblPtjObt;
    private javax.swing.JLabel LblReceptor;
    private javax.swing.JLabel LblReceptorValor;
    private javax.swing.JLabel LblRegionPos;
    private javax.swing.JLabel LblRegionSub;
    private javax.swing.JLabel LblRunCon;
    private javax.swing.JLabel LblRunPos;
    private javax.swing.JLabel LblSitio;
    private javax.swing.JLabel LblTipoVivienda;
    private javax.swing.JLabel LblTituloSub;
    private javax.swing.JLabel LblTituloVentana;
    private javax.swing.JLabel LblValorProp;
    private javax.swing.JPanel PanContacto;
    private javax.swing.JPanel PanDatosConyuge;
    private javax.swing.JPanel PanDatosPersonales;
    private javax.swing.JPanel PanDatosSubsidio;
    private javax.swing.JPanel PanDomicilio;
    private javax.swing.JTextField TxtBlock;
    private javax.swing.JTextField TxtCalle;
    private javax.swing.JTextField TxtCargas;
    private javax.swing.JTextField TxtCarrera;
    private javax.swing.JTextField TxtCodPostal;
    private javax.swing.JTextField TxtComunaPos;
    private javax.swing.JTextField TxtComunaSub;
    private javax.swing.JTextField TxtDepto;
    private javax.swing.JTextField TxtECivil;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtFecNac;
    private javax.swing.JTextField TxtFonoDom;
    private javax.swing.JTextField TxtFonoMovil;
    private javax.swing.JTextField TxtFonoTrab;
    private javax.swing.JTextField TxtIndOrg;
    private javax.swing.JTextField TxtManzana;
    private javax.swing.JTextField TxtMontoAhorrado;
    private javax.swing.JTextField TxtNacion;
    private javax.swing.JTextField TxtNomCon;
    private javax.swing.JTextField TxtNomPos;
    private javax.swing.JTextField TxtNumCalle;
    private javax.swing.JTextField TxtPtjMin;
    private javax.swing.JTextField TxtPtjObt;
    private javax.swing.JTextField TxtRegionPos;
    private javax.swing.JTextField TxtRegionSub;
    private javax.swing.JTextField TxtRunCon;
    private javax.swing.JTextField TxtRunPos;
    private javax.swing.JTextField TxtSitio;
    private javax.swing.JTextField TxtTipoVivienda;
    private javax.swing.JTextField TxtTituloSub;
    private javax.swing.JTextField TxtValorProp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
